const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"治疗信息管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaoxinxi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"确诊患者管理",
                        "menuJump":"列表",
                        "tableName":"quezhenhuanzhe"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"死亡患者管理",
                        "menuJump":"列表",
                        "tableName":"siwanghuanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"治愈患者管理",
                        "menuJump":"列表",
                        "tableName":"zhiyuhuanzhe"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"密切接触者管理",
                        "menuJump":"列表",
                        "tableName":"miqiejiechuzhe"
                    }
                ],
                "menu":"密切接触者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"治疗信息管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaoxinxi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"确诊患者管理",
                        "menuJump":"列表",
                        "tableName":"quezhenhuanzhe"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"死亡患者管理",
                        "menuJump":"列表",
                        "tableName":"siwanghuanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"治愈患者管理",
                        "menuJump":"列表",
                        "tableName":"zhiyuhuanzhe"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"密切接触者管理",
                        "menuJump":"列表",
                        "tableName":"miqiejiechuzhe"
                    }
                ],
                "menu":"密切接触者管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"员工",
        "tableName":"yuangong"
    }
]
    }
}
export default menu;
